"""empty message

Revision ID: 4a5c77533303
Revises: 74222e25b142
Create Date: 2025-09-21 01:15:34.283103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5c77533303'
down_revision = '74222e25b142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_world_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_user_id'))
        batch_op.drop_index(batch_op.f('ix_world_creation_date'))

    op.drop_table('world')
    # ### end Alembic commands ###
