"""empty message

Revision ID: 516cd86f85d8
Revises: 03a54cc63348
Create Date: 2025-10-05 00:42:44.819880

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "516cd86f85d8"
down_revision = "03a54cc63348"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
