"""added project description

Revision ID: 539d7f5a2474
Revises: e9fee7917a3e
Create Date: 2025-09-25 20:25:35.137858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539d7f5a2474'
down_revision = 'e9fee7917a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=280), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
