"""users table

Revision ID: 74222e25b142
Revises: 33ddf69aa958
Create Date: 2025-09-17 00:37:02.806437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74222e25b142'
down_revision = '33ddf69aa958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
